#ifndef __RESDEF_
#define __RESDEF_ 

#define PWDMAN_SUCCESS 200
#define PWDMAN_SUCCESSADD 201
#define PWDMAN_SUCCESSUPDATE 202
#define PWDMAN_SUCCESSDELETE 203
#define PWDMAN_SUCCESSFIND 204

#define PWDMAN_ERROR 400
#define PWDMAN_ERRINVALIDID 401
#define PWDMAN_ERRINVALIDEMAIL 402
#define PWDMAN_ERRINVALIDSITE 403
#define PWDMAN_ERRINVALIDPARAMS 404
#define PWDMAN_ERRIDNOTFOUND 405
#define PWDMAN_ERRSITENOTFOUND 406
#define PWDMAN_ERREMAILNOTFOUND 407


#endif